'''This file plots the orbits of all bodies in the solar system. It takes input from a binary data file, that is generated by "Simulation.py",
   and produces a plot of positions of the bodies 
'''
import matplotlib.pyplot as plt
import numpy as np
import Simulation

# Load the data from a file
Data = np.load("simulations/SolarSystem_1Year_Euler.npy", allow_pickle=True)

body_names = [
    "Sun",
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
]

# Set a colour palette for the orbit visualisation
colours = [
    "#ca2e55",
    "#ffe0b5",
    "#8a6552",
    "#462521",
    "#bdb246",
    "#8ae1fc",
    "#48b8d0",
    "#20a39e",
    "#23001e",
]

# Plot the results
for body_number, colour in zip(range(9), colours):
    plt.scatter(
        [bodies[body_number].position[0] for bodies in Data],
        [bodies[body_number].position[1] for bodies in Data],
        label=body_names[body_number],
        c=colour,
        marker=".",
        s=1,
    )
plt.xlabel("Position in x-direction")
plt.ylabel("Position in y-direction")
plt.legend()
plt.savefig("plots/Solar_System_1Year_Euler.pdf")
plt.show()
